/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RpgClock,
  urlRegex: () => urlRegex
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/clock.ts
var import_obsidian = require("obsidian");

// src/parse.ts
function parseClocks(input) {
  const defs = [];
  input.split("\n").forEach((line, lineOffset) => {
    if (!line.trim()) return;
    const parts = line.split(":");
    let name, value, color;
    if (parts.length === 1) {
      name = "";
      value = parts[0];
    } else if (parts.length === 2) {
      [name, value] = parts;
    } else {
      name = parts[0];
      value = parts[1];
      color = parts.slice(2).join(":");
    }
    const [filled, total] = value.split("/").map(Number);
    if (isNaN(filled) || isNaN(total)) return;
    defs.push({ name, filled, total, color, lineOffset });
  });
  return defs;
}
function serializeClock(def) {
  let line = `${def.name}:${def.filled}/${def.total}`;
  if (def.color) line += `:${def.color}`;
  return line;
}

// src/clock.ts
var Clock = class extends import_obsidian.MarkdownRenderChild {
  constructor(plugin, settings, containerEl, input, ctx) {
    super(containerEl);
    this.plugin = plugin;
    this.settings = settings;
    this.input = input;
    this.ctx = ctx;
    this.clockDefs = parseClocks(input);
  }
  onload() {
    this.containerEl.innerHTML = "";
    this.renderAll();
    if (this.plugin.pendingFocusLast) {
      this.plugin.pendingFocusLast = false;
      setTimeout(() => {
        var _a;
        const displays = this.containerEl.querySelectorAll(".clock-name-display");
        (_a = displays[displays.length - 1]) == null ? void 0 : _a.click();
      }, 0);
    }
  }
  unload() {
    var _a;
    if (this.clockDefs.length > 0) {
      (_a = this.plugin.clocks) == null ? void 0 : _a.remove(this);
    }
  }
  refresh() {
    this.clockDefs = parseClocks(this.input);
    this.containerEl.empty();
    this.renderAll();
  }
  renderAll() {
    var _a;
    const size = (_a = this.settings.clockSize) != null ? _a : 100;
    this.containerEl.style.display = "grid";
    this.containerEl.style.gridTemplateColumns = `repeat(auto-fill, minmax(${size + 40}px, 1fr))`;
    this.containerEl.style.gap = "8px";
    this.containerEl.style.alignItems = "start";
    const clockEls = [];
    for (const def of this.clockDefs) {
      clockEls.push(this.renderClock(this.containerEl, def));
    }
    clockEls.forEach((el, i) => this.setupDrag(el, i, clockEls));
    this.renderAddButton(this.containerEl);
  }
  renderClock(container, def) {
    var _a, _b;
    const color = def.color || this.settings.clockColor;
    const size = (_a = this.settings.clockSize) != null ? _a : 100;
    const clockEl = container.createDiv({ cls: "clock" });
    clockEl.setAttribute("n", String(def.total));
    clockEl.style.setProperty("--n", String(def.total));
    clockEl.style.setProperty("--clock-color", color);
    clockEl.style.setProperty("--clock-size", `${size}px`);
    const widgetEl = clockEl.createDiv({ cls: "widget" });
    widgetEl.createDiv({ cls: "clock-drag-handle", text: "\u283F" });
    const deleteBtn = widgetEl.createEl("button", { cls: "clock-delete-btn", text: "\xD7" });
    deleteBtn.addEventListener("click", async () => {
      const idx = this.clockDefs.indexOf(def);
      if (idx === -1) return;
      const file = this.plugin.app.vault.getAbstractFileByPath(this.ctx.sourcePath);
      if (!file) return;
      const info = this.ctx.getSectionInfo(this.containerEl);
      if (!info) return;
      this.clockDefs.splice(idx, 1);
      this.containerEl.empty();
      this.renderAll();
      await this.writeAllClocksWithInfo(file, info);
    });
    const coreEl = widgetEl.createDiv({ cls: "core" });
    this.buildSlices(coreEl, def.total, def.filled);
    this.buildBars(coreEl, def.total);
    const wireSliceHandlers = () => {
      coreEl.querySelectorAll(".slice").forEach((slice, i) => {
        slice.addEventListener("click", () => {
          def.filled = i + 1;
          filledVal.textContent = String(def.filled);
          this.updateFilledDOM(clockEl, def.filled);
          this.updateClockSource(def);
        });
      });
    };
    wireSliceHandlers();
    const colorBtn = widgetEl.createEl("button", { cls: "clock-color-btn" });
    colorBtn.style.background = color;
    const palette = (_b = this.settings.paletteColors) != null ? _b : [];
    const swatchRow = clockEl.createDiv({ cls: "clock-palette clock-palette--hidden" });
    for (const paletteColor of palette) {
      const swatch = swatchRow.createDiv({ cls: "clock-palette-swatch" });
      swatch.style.background = paletteColor;
      swatch.setAttribute("title", paletteColor);
      swatch.addEventListener("click", () => {
        def.color = paletteColor;
        clockEl.style.setProperty("--clock-color", paletteColor);
        colorBtn.style.background = paletteColor;
        swatchRow.addClass("clock-palette--hidden");
        this.updateClockSource(def);
      });
    }
    colorBtn.addEventListener("click", () => {
      swatchRow.toggleClass("clock-palette--hidden", !swatchRow.hasClass("clock-palette--hidden"));
    });
    const controlsEl = clockEl.createDiv({ cls: "clock-controls" });
    const stepperEl = controlsEl.createDiv({ cls: "clock-stepper" });
    const decBtn = stepperEl.createEl("button", { cls: "clock-btn-dec", text: "-" });
    const filledVal = stepperEl.createEl("span", { cls: "clock-filled-val", text: String(def.filled) });
    stepperEl.createEl("span", { cls: "clock-sep", text: "/" });
    const totalInput = stepperEl.createEl("input", { cls: "clock-total" });
    totalInput.type = "number";
    totalInput.min = "1";
    totalInput.max = "24";
    totalInput.value = String(def.total);
    totalInput.addEventListener("focus", () => totalInput.select());
    const incBtn = stepperEl.createEl("button", { cls: "clock-btn-inc", text: "+" });
    const nameDisplay = controlsEl.createEl("div", { cls: "clock-name-display" });
    nameDisplay.textContent = def.name || "Clock name";
    if (!def.name) nameDisplay.addClass("clock-name-display--placeholder");
    const nameInput = controlsEl.createEl("input", { cls: "clock-name clock-name--hidden" });
    nameInput.type = "text";
    nameInput.value = def.name;
    nameInput.placeholder = "Clock name";
    const enterEditMode = () => {
      nameDisplay.addClass("clock-name-display--hidden");
      nameInput.removeClass("clock-name--hidden");
      nameInput.focus();
      nameInput.select();
    };
    const exitEditMode = () => {
      def.name = nameInput.value;
      nameDisplay.textContent = def.name || "Clock name";
      nameDisplay.toggleClass("clock-name-display--placeholder", !def.name);
      nameInput.addClass("clock-name--hidden");
      nameDisplay.removeClass("clock-name-display--hidden");
      this.updateClockSource(def);
    };
    nameDisplay.addEventListener("click", enterEditMode);
    nameInput.addEventListener("blur", exitEditMode);
    nameInput.addEventListener("input", () => {
      nameInput.value = nameInput.value.replace(/:/g, "");
    });
    nameInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") nameInput.blur();
      if (e.key === "Escape") {
        nameInput.value = def.name;
        nameInput.blur();
      }
    });
    decBtn.addEventListener("click", () => {
      if (def.filled <= 0) return;
      def.filled--;
      filledVal.textContent = String(def.filled);
      this.updateFilledDOM(clockEl, def.filled);
      this.updateClockSource(def);
    });
    incBtn.addEventListener("click", () => {
      if (def.filled >= def.total) return;
      def.filled++;
      filledVal.textContent = String(def.filled);
      this.updateFilledDOM(clockEl, def.filled);
      this.updateClockSource(def);
    });
    totalInput.addEventListener("change", () => {
      const newTotal = parseInt(totalInput.value);
      if (isNaN(newTotal) || newTotal < 1) return;
      def.total = newTotal;
      def.filled = Math.min(def.filled, def.total);
      filledVal.textContent = String(def.filled);
      clockEl.setAttribute("n", String(def.total));
      clockEl.style.setProperty("--n", String(def.total));
      coreEl.empty();
      this.buildSlices(coreEl, def.total, def.filled);
      this.buildBars(coreEl, def.total);
      wireSliceHandlers();
      this.updateClockSource(def);
    });
    return clockEl;
  }
  // ── Drag & drop ──────────────────────────────────────────────────────────
  setupDrag(clockEl, index, allClockEls) {
    clockEl.draggable = true;
    clockEl.addEventListener("dragstart", (e) => {
      const target = e.target;
      if (target.closest("input, button")) {
        e.preventDefault();
        return;
      }
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", String(index));
      setTimeout(() => clockEl.addClass("clock-dragging"), 0);
    });
    clockEl.addEventListener("dragend", () => {
      clockEl.removeClass("clock-dragging");
      allClockEls.forEach((el) => el.removeClass("clock-drag-over"));
    });
    clockEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      e.dataTransfer.dropEffect = "move";
      allClockEls.forEach((el) => el.removeClass("clock-drag-over"));
      clockEl.addClass("clock-drag-over");
    });
    clockEl.addEventListener("dragleave", (e) => {
      if (!clockEl.contains(e.relatedTarget)) {
        clockEl.removeClass("clock-drag-over");
      }
    });
    clockEl.addEventListener("drop", (e) => {
      e.preventDefault();
      clockEl.removeClass("clock-drag-over");
      const fromIndex = parseInt(e.dataTransfer.getData("text/plain"));
      if (isNaN(fromIndex) || fromIndex === index) return;
      const [moved] = this.clockDefs.splice(fromIndex, 1);
      this.clockDefs.splice(index, 0, moved);
      this.containerEl.empty();
      this.renderAll();
      this.writeAllClocks();
    });
  }
  // ── Add clock ─────────────────────────────────────────────────────────────
  renderAddButton(container) {
    var _a;
    const size = (_a = this.settings.clockSize) != null ? _a : 100;
    const addBtn = container.createDiv({ cls: "clock-add" });
    addBtn.style.setProperty("--clock-size", `${size}px`);
    for (const sections of [4, 6, 8, 10]) {
      const opt = addBtn.createEl("button", { cls: "clock-add-opt" });
      opt.appendChild(this.buildClockPreviewSVG(sections));
      opt.createEl("span", { cls: "clock-add-label", text: `+ ${sections}` });
      opt.addEventListener("click", () => this.addClock(sections));
    }
  }
  buildClockPreviewSVG(sections) {
    const ns = "http://www.w3.org/2000/svg";
    const svg = document.createElementNS(ns, "svg");
    svg.setAttribute("viewBox", "0 0 40 40");
    svg.setAttribute("class", "clock-add-preview");
    const circle = document.createElementNS(ns, "circle");
    circle.setAttribute("cx", "20");
    circle.setAttribute("cy", "20");
    circle.setAttribute("r", "17");
    svg.appendChild(circle);
    for (let i = 0; i < sections; i++) {
      const angle = i / sections * 2 * Math.PI - Math.PI / 2;
      const line = document.createElementNS(ns, "line");
      line.setAttribute("x1", "20");
      line.setAttribute("y1", "20");
      line.setAttribute("x2", (20 + 17 * Math.cos(angle)).toFixed(2));
      line.setAttribute("y2", (20 + 17 * Math.sin(angle)).toFixed(2));
      svg.appendChild(line);
    }
    return svg;
  }
  async addClock(sections) {
    const file = this.plugin.app.vault.getAbstractFileByPath(this.ctx.sourcePath);
    if (!file) return;
    const info = this.ctx.getSectionInfo(this.containerEl);
    if (!info) return;
    const newDef = { name: "New Clock", filled: 0, total: sections, lineOffset: this.clockDefs.length };
    this.clockDefs.push(newDef);
    this.plugin.pendingFocusLast = true;
    await this.writeAllClocks();
  }
  // ── DOM helpers ───────────────────────────────────────────────────────────
  buildSlices(coreEl, total, filled) {
    for (let i = 0; i < total; i++) {
      const slice = coreEl.createDiv({ cls: "slice" });
      slice.setAttribute("i", String(i));
      slice.style.setProperty("--i", String(i));
      if (i < filled) slice.setAttribute("filled", "");
    }
  }
  buildBars(coreEl, total) {
    for (let i = 0; i < total; i++) {
      const bar = coreEl.createDiv({ cls: "bar" });
      bar.setAttribute("i", String(i));
      bar.style.setProperty("--i", String(i));
      bar.createDiv({ cls: "paint" });
    }
  }
  updateFilledDOM(clockEl, filled) {
    clockEl.querySelectorAll(".slice").forEach((slice, i) => {
      if (i < filled) slice.setAttribute("filled", "");
      else slice.removeAttribute("filled");
    });
  }
  /** Convert any CSS color string to #rrggbb for <input type="color"> */
  toHex(color) {
    if (/^#[0-9a-fA-F]{6}$/.test(color)) return color;
    const ctx = document.createElement("canvas").getContext("2d");
    if (!ctx) return "#ff5757";
    ctx.fillStyle = color;
    return ctx.fillStyle;
  }
  // ── Source writes ─────────────────────────────────────────────────────────
  async updateClockSource(def) {
    const file = this.plugin.app.vault.getAbstractFileByPath(this.ctx.sourcePath);
    if (!file) return;
    const info = this.ctx.getSectionInfo(this.containerEl);
    if (!info) return;
    const targetLine = info.lineStart + 1 + def.lineOffset;
    const content = await this.plugin.app.vault.read(file);
    const lines = content.split("\n");
    if (targetLine >= lines.length) return;
    lines[targetLine] = serializeClock(def);
    await this.plugin.app.vault.modify(file, lines.join("\n"));
  }
  async writeAllClocks() {
    const file = this.plugin.app.vault.getAbstractFileByPath(this.ctx.sourcePath);
    if (!file) return;
    const info = this.ctx.getSectionInfo(this.containerEl);
    if (!info) return;
    await this.writeAllClocksWithInfo(file, info);
  }
  async writeAllClocksWithInfo(file, info) {
    const content = await this.plugin.app.vault.read(file);
    const lines = content.split("\n");
    const blockStart = info.lineStart + 1;
    const blockEnd = info.lineEnd;
    const newLines = this.clockDefs.map(serializeClock);
    lines.splice(blockStart, blockEnd - blockStart, ...newLines);
    await this.plugin.app.vault.modify(file, lines.join("\n"));
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DefaultSettings = {
  clockSize: 150,
  clockColor: "#70909e",
  paletteColors: [
    "#1f0000",
    "#ab1212",
    "#006d75",
    "#c8d6e5",
    "#ffffff",
    "#caa212",
    "#6e8776"
  ]
};
var SettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    let { settings } = this.plugin;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Clock Size").setDesc("How big the clock will be.").addSlider((slider) => {
      slider.setLimits(60, 300, 10).setValue(settings.clockSize).setDynamicTooltip().onChange(async (value) => {
        var _a;
        settings.clockSize = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.clocks) == null ? void 0 : _a.forEach((c) => c.refresh());
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Clock Color").setDesc("Default clock color on creation.").addColorPicker((colorPicker) => {
      colorPicker.setValue(settings.clockColor).onChange(async (value) => {
        settings.clockColor = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Color Palette").setDesc("Quick-select colors available on each clock. Click a swatch to remove it.");
    const paletteWrap = containerEl.createDiv({ cls: "rpg-clock-palette-editor" });
    this.renderPaletteEditor(paletteWrap);
  }
  renderPaletteEditor(wrap) {
    wrap.empty();
    const { settings } = this.plugin;
    const swatchRow = wrap.createDiv({ cls: "rpg-clock-palette-swatches" });
    let dragFrom = null;
    for (let i = 0; i < settings.paletteColors.length; i++) {
      const color = settings.paletteColors[i];
      const swatch = swatchRow.createDiv({ cls: "rpg-clock-palette-swatch" });
      swatch.style.background = color;
      swatch.setAttribute("title", `${color} \u2014 click to edit, right-click to remove`);
      swatch.draggable = true;
      const colorPicker = swatch.createEl("input", { cls: "rpg-clock-palette-swatch-picker" });
      colorPicker.type = "color";
      colorPicker.value = color;
      colorPicker.addEventListener("input", async () => {
        settings.paletteColors[i] = colorPicker.value;
        swatch.style.background = colorPicker.value;
        swatch.setAttribute("title", `${colorPicker.value} \u2014 click to edit, right-click to remove`);
        await this.plugin.saveSettings();
      });
      swatch.addEventListener("click", () => colorPicker.click());
      swatch.addEventListener("contextmenu", async (e) => {
        e.preventDefault();
        settings.paletteColors.splice(i, 1);
        await this.plugin.saveSettings();
        this.renderPaletteEditor(wrap);
      });
      swatch.addEventListener("dragstart", (e) => {
        dragFrom = i;
        e.dataTransfer.effectAllowed = "move";
        setTimeout(() => swatch.addClass("rpg-clock-palette-swatch--dragging"), 0);
      });
      swatch.addEventListener("dragend", () => {
        dragFrom = null;
        swatchRow.querySelectorAll(".rpg-clock-palette-swatch").forEach((el) => {
          el.removeClass("rpg-clock-palette-swatch--dragging");
          el.removeClass("rpg-clock-palette-swatch--over");
        });
      });
      swatch.addEventListener("dragover", (e) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = "move";
        swatchRow.querySelectorAll(".rpg-clock-palette-swatch").forEach(
          (el) => el.removeClass("rpg-clock-palette-swatch--over")
        );
        swatch.addClass("rpg-clock-palette-swatch--over");
      });
      swatch.addEventListener("dragleave", (e) => {
        if (!swatch.contains(e.relatedTarget))
          swatch.removeClass("rpg-clock-palette-swatch--over");
      });
      swatch.addEventListener("drop", async (e) => {
        e.preventDefault();
        swatch.removeClass("rpg-clock-palette-swatch--over");
        if (dragFrom === null || dragFrom === i) return;
        const [moved] = settings.paletteColors.splice(dragFrom, 1);
        settings.paletteColors.splice(i, 0, moved);
        await this.plugin.saveSettings();
        this.renderPaletteEditor(wrap);
      });
    }
    const addRow = wrap.createDiv({ cls: "rpg-clock-palette-add-row" });
    const picker = addRow.createEl("input", { cls: "rpg-clock-palette-picker" });
    picker.type = "color";
    picker.value = "#ffffff";
    const addBtn = addRow.createEl("button", { text: "Add color" });
    addBtn.addEventListener("click", async () => {
      const color = picker.value;
      if (!settings.paletteColors.includes(color)) {
        settings.paletteColors.push(color);
        await this.plugin.saveSettings();
        this.renderPaletteEditor(wrap);
      }
    });
  }
  hide() {
    var _a;
    if ((_a = this.plugin) == null ? void 0 : _a.clocks) {
      for (let palette of this.plugin.clocks) {
        palette.refresh();
      }
    }
  }
};

// src/commandInput.ts
var import_obsidian3 = require("obsidian");
var CommandInput = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.result = "";
    this.sections = 4;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "New Clock" });
    new import_obsidian3.Setting(contentEl).setName("Name").addText((text) => {
      text.onChange((value) => {
        this.result = value;
      });
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          this.onSubmit(this.result, this.sections);
          this.close();
        }
      });
      setTimeout(() => text.inputEl.focus(), 10);
    });
    new import_obsidian3.Setting(contentEl).setName("Sections").addText((text) => {
      text.setValue("4");
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.inputEl.max = "24";
      text.onChange((v) => {
        this.sections = parseInt(v) || 4;
      });
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          this.onSubmit(this.result, this.sections);
          this.close();
        }
      });
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create").setCta().onClick(() => {
        this.onSubmit(this.result, this.sections);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var urlRegex = /\/([^\/]+)\/?$/;
var RpgClock = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.pendingFocusLast = false;
  }
  async onload() {
    this.clocks = [];
    await this.loadSettings();
    this.registerMarkdownCodeBlockProcessor(
      "clock",
      async (source, el, ctx) => {
        ctx.addChild(new Clock(this, this.settings, el, source.trim(), ctx));
      }
    );
    this.addCommand({
      id: "insert-clock",
      name: "Insert Clock",
      editorCallback: (editor) => {
        new CommandInput(this.app, (name, sections) => {
          this.insertClockAtCursor(editor, name, sections);
        }).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        menu.addItem((item) => {
          item.setTitle("Insert Clock").setIcon("clock").onClick(() => {
            new CommandInput(this.app, (name, sections) => {
              this.insertClockAtCursor(editor, name, sections);
            }).open();
          });
        });
      })
    );
    this.addSettingTab(new SettingsTab(this.app, this));
  }
  insertClockAtCursor(editor, name, sections) {
    try {
      const codeBlock = `\`\`\`clock
${name}:0/${sections}
\`\`\`
`;
      const cursor = editor.getCursor();
      editor.transaction({
        changes: [{ from: cursor, text: codeBlock }]
      });
      editor.setCursor({
        line: cursor.line + codeBlock.split("\n").length,
        ch: 0
      });
      new import_obsidian4.Notice(`Added ${name}`);
    } catch (error) {
      new import_obsidian4.Notice(String(error));
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DefaultSettings, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
